#!/usr/bin/env python3
"""Parse an RPG Maker playthrough log generated by TimelineLogger.js.

Usage:
    python3 parse_playthrough_log.py <log_path> --map-index <map_index_path> -o <output_path>
"""
import argparse
import json
import os
import re
import sys


def parse_log(log_path: str, map_index: dict | None = None) -> dict:
    events = []
    current_map = None

    with open(log_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Common TimelineLogger patterns
    timestamp_re = re.compile(r"^\[(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})\]\s*(.+)")
    map_change_re = re.compile(r"Map\s*(?:Change|Transfer|Move).*?(?:Map\s*)?(\d+)", re.IGNORECASE)
    dialogue_re = re.compile(r"(?:Dialogue|Message|Text)\s*[:\-]\s*(.+)", re.IGNORECASE)
    choice_re = re.compile(r"(?:Choice|Select)\s*[:\-]\s*(.+)", re.IGNORECASE)
    event_re = re.compile(r"(?:Event|Trigger|CommonEvent)\s*[:\-]\s*(.+)", re.IGNORECASE)

    for line_num, line in enumerate(lines, 1):
        line = line.strip()
        if not line:
            continue

        timestamp = None
        content = line

        # Extract timestamp if present
        ts_match = timestamp_re.match(line)
        if ts_match:
            timestamp = ts_match.group(1)
            content = ts_match.group(2)

        event = {
            "line": line_num,
            "timestamp": timestamp,
            "raw": content,
            "type": "unknown",
            "map_id": current_map,
        }

        # Classify event type
        if map_change_re.search(content):
            match = map_change_re.search(content)
            current_map = int(match.group(1))
            event["type"] = "map_change"
            event["map_id"] = current_map
            if map_index and str(current_map) in map_index.get("maps", {}):
                event["map_name"] = map_index["maps"][str(current_map)].get("display_name", "")
        elif dialogue_re.search(content):
            event["type"] = "dialogue"
            event["content"] = dialogue_re.search(content).group(1).strip()
        elif choice_re.search(content):
            event["type"] = "choice"
            event["content"] = choice_re.search(content).group(1).strip()
        elif event_re.search(content):
            event["type"] = "event_trigger"
            event["content"] = event_re.search(content).group(1).strip()

        events.append(event)

    # Build summary
    type_counts = {}
    for e in events:
        type_counts[e["type"]] = type_counts.get(e["type"], 0) + 1

    return {
        "total_entries": len(events),
        "type_counts": type_counts,
        "unique_maps_visited": len(set(e["map_id"] for e in events if e["map_id"] is not None)),
        "events": events,
    }


def main():
    parser = argparse.ArgumentParser(description="Parse RPG Maker playthrough log")
    parser.add_argument("log_path", help="Path to playthrough_log.txt")
    parser.add_argument("--map-index", help="Path to map_index.json for map name resolution")
    parser.add_argument("-o", "--output", required=True, help="Output JSON file path")
    args = parser.parse_args()

    if not os.path.isfile(args.log_path):
        print(f"Error: {args.log_path} not found", file=sys.stderr)
        sys.exit(1)

    map_index = None
    if args.map_index and os.path.isfile(args.map_index):
        with open(args.map_index, "r", encoding="utf-8") as f:
            map_index = json.load(f)

    result = parse_log(args.log_path, map_index)

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"Parsed {result['total_entries']} entries → {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
